# Generated by Django 4.0.2 on 2022-02-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='num1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='num2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='num3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='num4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
