# Generated by Django 4.0.2 on 2022-02-26 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdapp', '0003_alter_item_num1_alter_item_num2_alter_item_num3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='num1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='num1', to='pdapp.numbers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='num2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='num2', to='pdapp.numbers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='num3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='num3', to='pdapp.numbers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='num4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='num4', to='pdapp.numbers'),
            preserve_default=False,
        ),
    ]
