# Generated by Django 4.0.2 on 2022-03-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0004_numbers_delete_home_alter_item_user_alter_item_num1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='num1',
            new_name='NumItem',
        ),
        migrations.RemoveField(
            model_name='item',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='num3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='num4',
        ),
    ]
