# Generated by Django 4.0.2 on 2022-03-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0005_rename_num1_item_numitem_remove_item_num2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
